# NovaCorp People Analytics Starter Notebook

This notebook loads the four CSV files in this folder using pandas and shows a first look at each dataset. Use it as the starting point for exploring the hackathon case.

In [1]:
from pathlib import Path

import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", 140)
pd.set_option("display.width", 220)

DATA_DIR = Path.cwd()
DATA_DIR

WindowsPath('c:/Users/felix/OneDrive/Desktop/GitHappens_AccentureXUSYDDatathon')

In [2]:
employees = pd.read_csv(DATA_DIR / "employees.csv")
attrition_log = pd.read_csv(DATA_DIR / "attrition_log.csv")
engagement = pd.read_csv(DATA_DIR / "engagement.csv")
performance = pd.read_csv(DATA_DIR / "performance.csv")

datasets = {
    "employees": employees,
    "attrition_log": attrition_log,
    "engagement": engagement,
    "performance": performance,
}

pd.DataFrame(
    {
        "dataset": name,
        "rows": len(df),
        "columns": df.shape[1],
    }
    for name, df in datasets.items()
)

         dataset   rows  columns
0      employees  13403       24
1  attrition_log   1400       10
2     engagement  55971       12
3    performance  34979        7

## employees.csv

Employee master data. This is the workforce spine for joining department, role, compensation, demographics, tenure, manager, hire source, and acquisition cohort context to other datasets.

In [3]:
employees.head()

,employee_id,name,hire_date,exit_date,status,department,role_family,role_level,job_title,salary,compa_ratio,gender,age_band,cultural_background,contract_type,hipo_flag,promotion_eligible,manager_id,hire_source,legacy_entity_code,data_source_system,days_to_fill,tenure_months,acting_appointment
0,E00001,Madison Lang,1988-01-11,NaN,active,Wealth Management,Operations-Processing,2,"Manager, Wealth Management",115200.0,0.79,Female,60+,Anglo-Australian,Full-time,False,False,E04330,referral,NovaCorp-Origin,WorkdayHR,22.0,462,False
1,E00003,Amy Garza,1988-01-13,NaN,active,Wealth Management,Corporate-Support,3,"Senior Manager, Wealth Management",170200.0,0.85,Female,60+,South Asian,Full-time,False,False,E13109,direct,NovaCorp-Origin,WorkdayHR,62.0,462,False
2,E00004,Meghan Robertson,1988-01-14,NaN,active,Insurance,Management,2,"Manager, Insurance",125500.0,0.87,Female,60+,East Asian,Full-time,False,False,E14294,referral,NovaCorp-Origin,WorkdayHR,86.0,462,False
3,E00005,Gabrielle Crawford,1988-01-14,2024-12-24,departed,Wealth Management,Technology,2,"Manager, Wealth Management",132400.0,0.91,Female,60+,East Asian,Full-time,False,True,E12337,direct,NovaCorp-Origin,WorkdayHR,63.0,449,False
4,E00006,Karen Hernandez,1988-01-15,2025-04-17,departed,Corporate Operations,Risk-Compliance,2,"Manager, Corporate Operations",120600.0,0.83,Female,60+,Anglo-Australian,Full-time,False,False,E00218,agency,NovaCorp-Origin,WorkdayHR,20.0,453,False

In [4]:
employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 13403 entries, 0 to 13402
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   employee_id          13403 non-null  str
 1   name                 13403 non-null  str
 2   hire_date            13403 non-null  str
 3   exit_date            1400 non-null   str
 4   status               13403 non-null  str
 5   department           13403 non-null  str
 6   role_family          13403 non-null  str
 7   role_level           13403 non-null  int64
 8   job_title            13403 non-null  str
 9   salary               13403 non-null  float64
 10  compa_ratio          13403 non-null  float64
 11  gender               13403 non-null  str
 12  age_band             13403 non-null  str
 13  cultural_background  13403 non-null  str
 14  contract_type        13403 non-null  str
 15  hipo_flag            13403 non-null  bool
 16  promotion_eligible   13403 non-null  bool
 17  manager_id           13402 non-null  str
 18  hire_source          13403 non-null  str
 19  legacy_entity_code   13403 non-null  str
 20  data_source_system   13403 non-null  str
 21  days_to_fill         13403 non-null  float64
 22  tenure_months        13403 non-null  int64
 23  acting_appointment   13403 non-null  bool
dtypes: bool(3), float64(3), int64(2), str(16)
memory usage: 4.2 MB

## attrition_log.csv

Exit records. This is the main outcome dataset for analyzing voluntary/involuntary exits, stated reasons, regrettable attrition, performance band at exit, and exit timing.

In [5]:
attrition_log.head()

  employee_id   exit_date  exit_type  stated_exit_reason  notice_period_served  regrettable_flag performance_band_at_exit  salary_at_exit manager_id_at_exit pathway
0      E00005  2024-12-24  voluntary          Relocation                  True             False       Meets Expectations        132400.0             E12337    push
1      E00006  2025-04-17  voluntary   Work-life balance                  True             False       Below Expectations        120600.0             E00218    push
2      E00008  2024-02-19  voluntary  Career advancement                  True             False       Meets Expectations        117800.0             E00249    push
3      E00021  2024-05-24  voluntary  Career advancement                  True             False       Meets Expectations        125500.0             E08861    push
4      E00023  2025-07-04  voluntary  Career advancement                 False             False              Outstanding        175400.0             E09824    pull

In [6]:
attrition_log.info()

<class 'pandas.DataFrame'>
RangeIndex: 1400 entries, 0 to 1399
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   employee_id               1400 non-null   str
 1   exit_date                 1400 non-null   str
 2   exit_type                 1400 non-null   str
 3   stated_exit_reason        1400 non-null   str
 4   notice_period_served      1400 non-null   bool
 5   regrettable_flag          1400 non-null   bool
 6   performance_band_at_exit  1400 non-null   str
 7   salary_at_exit            1400 non-null   float64
 8   manager_id_at_exit        1400 non-null   str
 9   pathway                   1400 non-null   str
dtypes: bool(2), float64(1), str(7)
memory usage: 186.6 KB

## engagement.csv

Employee survey waves. This helps explain possible leading indicators behind attrition: manager effectiveness, psychological safety, recognition, career development, leadership trust, purpose, wellbeing, and confidence.

In [7]:
engagement.head()

  employee_id  wave_number survey_date  response_flag  manager_effectiveness  psychological_safety  recognition  career_development  senior_leadership_trust  purpose_meaning  wellbeing  confidence_in_role_future
0      E00001            1  2024-03-08           True                   5.00                  4.39         4.55                4.25                     3.72             3.47       4.83                       4.57
1      E00001            2  2024-06-27           True                   4.69                  4.26         4.10                3.52                     3.57             4.00       4.79                       4.71
2      E00001            3  2024-10-25           True                   4.65                  4.67         4.87                3.72                     3.51             3.80       4.52                       4.34
3      E00001            4  2025-01-31           True                   4.25                  5.00         5.00                3.29                     4.90             4.69       5.00                       4.46
4      E00001            5  2025-08-05           True                   4.57                  4.34         5.00                3.78                     4.57             3.75       4.46                       4.37

In [8]:
engagement.info()

<class 'pandas.DataFrame'>
RangeIndex: 55971 entries, 0 to 55970
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   employee_id                55971 non-null  str
 1   wave_number                55971 non-null  int64
 2   survey_date                55971 non-null  str
 3   response_flag              55971 non-null  bool
 4   manager_effectiveness      45707 non-null  float64
 5   psychological_safety       45707 non-null  float64
 6   recognition                45707 non-null  float64
 7   career_development         45707 non-null  float64
 8   senior_leadership_trust    45707 non-null  float64
 9   purpose_meaning            45707 non-null  float64
 10  wellbeing                  45707 non-null  float64
 11  confidence_in_role_future  45707 non-null  float64
dtypes: bool(1), float64(8), int64(1), str(2)
memory usage: 5.6 MB

## performance.csv

Performance review data. This lets you test whether attrition is concentrated among strong performers, promotion-ready employees, or specific review cycles.

In [9]:
performance.head()

  employee_id review_date  performance_rating review_cycle  promotion_recommendation  goal_achievement_score reviewer_id
0      E00001  2024-06-01  Meets Expectations      2024-H1                     False                    46.1      E04330
1      E00001  2024-11-21  Meets Expectations      2024-H2                     False                    65.4      E04330
2      E00001  2025-05-28  Meets Expectations      2025-H1                     False                    76.4      E04330
3      E00003  2024-06-15  Meets Expectations      2024-H1                     False                    67.0      E13109
4      E00003  2024-12-26      High Performer      2024-H2                      True                    68.7      E13109

In [10]:
performance.info()

<class 'pandas.DataFrame'>
RangeIndex: 34979 entries, 0 to 34978
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   employee_id               34979 non-null  str
 1   review_date               34979 non-null  str
 2   performance_rating        34979 non-null  str
 3   review_cycle              34979 non-null  str
 4   promotion_recommendation  34979 non-null  bool
 5   goal_achievement_score    34979 non-null  float64
 6   reviewer_id               34979 non-null  str
dtypes: bool(1), float64(1), str(5)
memory usage: 3.1 MB

## Quick Column Overview

In [11]:
for name, df in datasets.items():
    print(f"\n{name} ({df.shape[0]:,} rows x {df.shape[1]:,} columns)")
    display(pd.DataFrame({"column": df.columns, "dtype": df.dtypes.astype(str).values}))

employees (13,403 rows x 24 columns)

                 column    dtype
0           employee_id      str
1                  name      str
2             hire_date      str
3             exit_date      str
4                status      str
5            department      str
6           role_family      str
7            role_level    int64
8             job_title      str
9                salary  float64
10          compa_ratio  float64
11               gender      str
12             age_band      str
13  cultural_background      str
14        contract_type      str
15            hipo_flag     bool
16   promotion_eligible     bool
17           manager_id      str
18          hire_source      str
19   legacy_entity_code      str
20   data_source_system      str
21         days_to_fill  float64
22        tenure_months    int64
23   acting_appointment     bool

attrition_log (1,400 rows x 10 columns)

                     column    dtype
0               employee_id      str
1                 exit_date      str
2                 exit_type      str
3        stated_exit_reason      str
4      notice_period_served     bool
5          regrettable_flag     bool
6  performance_band_at_exit      str
7            salary_at_exit  float64
8        manager_id_at_exit      str
9                   pathway      str

engagement (55,971 rows x 12 columns)

                       column    dtype
0                 employee_id      str
1                 wave_number    int64
2                 survey_date      str
3               response_flag     bool
4       manager_effectiveness  float64
5        psychological_safety  float64
6                 recognition  float64
7          career_development  float64
8     senior_leadership_trust  float64
9             purpose_meaning  float64
10                  wellbeing  float64
11  confidence_in_role_future  float64

performance (34,979 rows x 7 columns)

                     column    dtype
0               employee_id      str
1               review_date      str
2        performance_rating      str
3              review_cycle      str
4  promotion_recommendation     bool
5    goal_achievement_score  float64
6               reviewer_id      str

## Null Value Check

This prints the list of columns that contain at least one null value in each dataset.

In [12]:
null_columns_by_dataset = {}

for name, df in datasets.items():
    null_columns = df.columns[df.isna().any()].tolist()
    null_columns_by_dataset[name] = null_columns
    print(f"{name}: {null_columns}")

null_columns_by_dataset

employees: ['exit_date', 'manager_id']
attrition_log: []
engagement: ['manager_effectiveness', 'psychological_safety', 'recognition', 'career_development', 'senior_leadership_trust', 'purpose_meaning', 'wellbeing', 'confidence_in_role_future']
performance: []

{'employees': ['exit_date', 'manager_id'],
 'attrition_log': [],
 'engagement': ['manager_effectiveness',
  'psychological_safety',
  'recognition',
  'career_development',
  'senior_leadership_trust',
  'purpose_meaning',
  'wellbeing',
  'confidence_in_role_future'],
 'performance': []}

In [13]:
# Drop rows with any null values from each dataset
cleaned_datasets = {name: df.dropna() for name, df in datasets.items()}

# Show before/after row counts
pd.DataFrame(
    [
        {
            "dataset": name,
            "rows_before": len(df),
            "rows_after": len(cleaned_datasets[name]),
            "rows_dropped": len(df) - len(cleaned_datasets[name]),
        }
        for name, df in datasets.items()
    ]
)

         dataset  rows_before  rows_after  rows_dropped
0      employees        13403        1400         12003
1  attrition_log         1400        1400             0
2     engagement        55971       45707         10264
3    performance        34979       34979             0

In [ ]:
# STEP 1: Funnel & driver split
emp = datasets["employees"].copy()
attr = datasets["attrition_log"].copy()
emp["hire_date"] = pd.to_datetime(emp["hire_date"], errors="coerce")
emp["exit_date"] = pd.to_datetime(emp["exit_date"], errors="coerce")
attr["exit_date"] = pd.to_datetime(attr["exit_date"], errors="coerce")

ref_date = emp["exit_date"].max()
headcount = (emp["hire_date"] <= ref_date).sum()
n_all = len(attr)
n_vol = (attr["exit_type"] == "voluntary").sum()
n_reg = (attr["regrettable_flag"] == True).sum()

funnel = pd.DataFrame({
    "stage": ["Headcount FY25", "All exits", "Voluntary", "Regrettable"],
    "count": [headcount, n_all, n_vol, n_reg],
    "rate_vs_headcount_pct": [
        100.0,
        round(n_all/headcount*100, 2),
        round(n_vol/headcount*100, 2),
        round(n_reg/headcount*100, 2),
    ],
})
display(funnel)

print("
Push vs Pull split (%):")
print(attr["pathway"].value_counts(normalize=True).mul(100).round(2))

print("
Top exit reasons — all (%):")
print(attr["stated_exit_reason"].value_counts(normalize=True).mul(100).round(2).head(5))

print("
Top exit reasons — regrettable (%):")
print(attr.loc[attr["regrettable_flag"], "stated_exit_reason"].value_counts(normalize=True).mul(100).round(2).head(5))

In [ ]:
# STEP 2: Department & role-level hotspots
reg_full = attr.loc[attr["regrettable_flag"]].merge(
    emp[["employee_id", "department", "role_level"]],
    on="employee_id", how="left",
)

dept_hc = emp.groupby("department").size()
dept_reg = reg_full.groupby("department").size()
dept_tbl = pd.DataFrame({
    "headcount": dept_hc,
    "regrettable_exits": dept_reg.fillna(0).astype(int),
}).assign(
    reg_rate_pct=lambda d: round(d["regrettable_exits"]/d["headcount"]*100, 2),
    share_of_reg_pct=lambda d: round(d["regrettable_exits"]/n_reg*100, 2),
).sort_values("regrettable_exits", ascending=False)
display(dept_tbl)

lvl_hc = emp.groupby("role_level").size()
lvl_reg = reg_full.groupby("role_level").size()
lvl_tbl = pd.DataFrame({
    "headcount": lvl_hc,
    "regrettable_exits": lvl_reg.fillna(0).astype(int),
}).assign(
    reg_rate_pct=lambda d: round(d["regrettable_exits"]/d["headcount"]*100, 2),
    share_of_reg_pct=lambda d: round(d["regrettable_exits"]/n_reg*100, 2),
).sort_index()
display(lvl_tbl)

frontline = lvl_tbl.loc[lvl_tbl.index.isin([1,2,3]), "regrettable_exits"].sum()
print(f"
Frontline (L1-L3) share of regrettable: {frontline/n_reg*100:.2f}%")

In [ ]:
# STEP 3: Statistical tests — z-test per dept, Welch's t for engagement, chi-square for HiPO
from scipy import stats

# 3a) Per-dept z-test vs 9% benchmark
rows = []
for dept, row in dept_tbl.iterrows():
    n = int(row["headcount"])
    x = int(row["regrettable_exits"])
    p_hat = x/n
    p0 = 0.09
    se = (p0*(1-p0)/n)**0.5
    z = (p_hat - p0)/se
    p = 1 - stats.norm.cdf(z)
    rows.append({
        "department": dept, "n": n, "reg_exits": x,
        "rate_pct": round(p_hat*100, 2),
        "z": round(z, 3), "p_value": round(p, 4),
        "sig_above_9pct": p < 0.05,
    })
z_df = pd.DataFrame(rows).sort_values("rate_pct", ascending=False)
display(z_df)

# 3b) Engagement: regrettable vs retained (last wave)
eng = datasets["engagement"].copy()
score_cols = [
    "manager_effectiveness","psychological_safety","recognition",
    "career_development","senior_leadership_trust","purpose_meaning",
    "wellbeing","confidence_in_role_future",
]
last_wave = (
    eng.sort_values(["employee_id","wave_number"])
       .groupby("employee_id").tail(1)[["employee_id"]+score_cols]
       .merge(attr[["employee_id","regrettable_flag"]], on="employee_id", how="left")
)
last_wave["regrettable"] = last_wave["regrettable_flag"].fillna(False)

t_rows = []
for c in score_cols:
    g = last_wave.loc[last_wave["regrettable"], c].dropna()
    r = last_wave.loc[~last_wave["regrettable"], c].dropna()
    t, p = stats.ttest_ind(g, r, equal_var=False)
    pooled = pd.concat([g, r]).std()
    d = (g.mean() - r.mean()) / pooled if pooled > 0 else 0
    t_rows.append({
        "dimension": c,
        "reg_mean": round(g.mean(), 3),
        "ret_mean": round(r.mean(), 3),
        "diff": round(g.mean()-r.mean(), 3),
        "t": round(t, 3), "p_value": round(p, 6),
        "cohens_d": round(d, 3),
        "n_reg": len(g), "n_ret": len(r),
    })
t_df = pd.DataFrame(t_rows).sort_values("p_value")
display(t_df)

# 3c) HiPO / promotion chi-square
for flag in ["hipo_flag", "promotion_eligible"]:
    base = emp[flag].mean()
    reg_rate = reg_full.merge(emp[["employee_id", flag]], on="employee_id")[flag].mean()
    x = int(reg_full.merge(emp[["employee_id", flag]], on="employee_id")[flag].sum())
    n = len(reg_full)
    exp = base * n
    chi2 = (x - exp)**2 / exp if exp > 0 else 0
    p = 1 - stats.chi2.cdf(chi2, df=1)
    lift = (reg_rate/base - 1)*100 if base > 0 else 0
    print(f"{flag}: baseline={base*100:.2f}%, regrettable={reg_rate*100:.2f}%, "
          f"lift=+{lift:.1f}%, chi2={chi2:.2f}, p={p:.4f}")

In [ ]:
# STEP 4: Cost by department
total_cost = 45_800_000
reg_share = n_reg / n_all
reg_cost = total_cost * reg_share
print(f"Total annual attrition cost: A${total_cost:,}")
print(f"Regrettable share: {reg_share*100:.2f}%")
print(f"Estimated regrettable cost: A${reg_cost:,.0f}")

dept_cost = dept_tbl.assign(
    est_cost_aud=lambda d: round(d["share_of_reg_pct"]/100 * reg_cost, 0)
).sort_values("est_cost_aud", ascending=False)
display(dept_cost[["regrettable_exits", "share_of_reg_pct", "reg_rate_pct", "est_cost_aud"]])

In [ ]:
# LENS 1: Timing & Tenure
# When do exits cluster? What tenure bands attrite most?
import numpy as np

attr_full = attr.merge(emp[["employee_id","hire_date","department","role_level"]], on="employee_id", how="left")
attr_full["tenure_at_exit_months"] = ((attr_full["exit_date"] - attr_full["hire_date"]).dt.days / 30.25).round(1)

# Tenure bands
def tenure_band(m):
    if m < 12: return "<1 yr"
    if m < 24: return "1-2 yrs"
    if m < 60: return "2-5 yrs"
    if m < 120: return "5-10 yrs"
    return "10+ yrs"
attr_full["tenure_band"] = attr_full["tenure_at_exit_months"].apply(tenure_band)

ten = attr_full["tenure_band"].value_counts(normalize=True).mul(100).round(2)
print("Tenure at exit — all (%):")
print(ten)

reg_ten = attr_full.loc[attr_full["regrettable_flag"], "tenure_band"].value_counts(normalize=True).mul(100).round(2)
print("\nTenure at exit — regrettable (%):")
print(reg_ten)

# Exit by quarter
attr_full["exit_quarter"] = attr_full["exit_date"].dt.to_period("Q").astype(str)
q = attr_full["exit_quarter"].value_counts().sort_index()
print("\nExits by quarter:")
print(q)

# Regrettable rate by tenure band vs overall
ten_reg = attr_full.groupby("tenure_band").agg(
    exits=("employee_id","count"),
    reg=("regrettable_flag","sum"),
).assign(reg_rate=lambda d: round(d["reg"]/d["exits"]*100,2))
print("\nRegrettable rate by tenure band:")
display(ten_reg)

In [ ]:
# LENS 2: Manager as unit of analysis
# Which managers lose the most regrettable talent?
mgr = attr_full.loc[attr_full["regrettable_flag"]].groupby("manager_id_at_exit").agg(
    regrettable_exits=("employee_id","count"),
    depts=("department", lambda x: x.nunique()),
).sort_values("regrettable_exits", ascending=False)

print("Top 15 managers by regrettable exits:")
print(mgr.head(15).to_string())

multi = (mgr["regrettable_exits"] >= 2).sum()
print(f"\nManagers with 2+ regrettable exits: {multi} ({multi/len(mgr)*100:.1f}% of exit-managers)")

from scipy import stats as st
n_mgr = len(mgr)
total_reg = mgr["regrettable_exits"].sum()
expected = total_reg / n_mgr
observed_top10 = mgr.head(10)["regrettable_exits"].sum()
chi2_conc = (observed_top10 - 10*expected)**2 / (10*expected) + \
            ((total_reg - observed_top10) - (n_mgr-10)*expected)**2 / ((n_mgr-10)*expected)
p_conc = 1 - st.chi2.cdf(chi2_conc, df=1)
print(f"\nTop-10 managers hold {observed_top10/total_reg*100:.1f}% of regrettable exits")
print(f"Chi-square concentration test: chi2={chi2_conc:.2f}, p={p_conc:.6f}")

In [ ]:
# LENS 3: Career pathway — acting appointments, promotion eligibility
emp_c = emp.copy()
emp_c["is_leaver"] = emp_c["exit_date"].notna()

acting_rate = emp_c.groupby("acting_appointment")["is_leaver"].mean().mul(100).round(2)
print("Attrition rate by acting_appointment (%):")
print(acting_rate)

ct = pd.crosstab(emp_c["acting_appointment"], emp_c["is_leaver"])
chi2_a, p_a, _, _ = st.chi2_contingency(ct)
print(f"\nActing-appointment chi2={chi2_a:.2f}, p={p_a:.6f}")

ct2 = pd.crosstab(emp_c["promotion_eligible"], emp_c["is_leaver"])
chi2_p, p_p, _, _ = st.chi2_contingency(ct2)
print(f"Promotion-eligible chi2={chi2_p:.2f}, p={p_p:.6f}")

promo_leavers = emp_c.loc[emp_c["is_leaver"], "promotion_eligible"].mean()*100
promo_stayers = emp_c.loc[~emp_c["is_leaver"], "promotion_eligible"].mean()*100
print(f"\nPromotion-eligible: leavers={promo_leavers:.2f}%, stayers={promo_stayers:.2f}%")

In [ ]:
# LENS 4: Compensation — compa-ratio, salary at exit
emp_c2 = emp.copy()
emp_c2["is_leaver"] = emp_c2["exit_date"].notna()

emp_c2["comp_band"] = pd.cut(emp_c2["compa_ratio"], bins=[0, 0.85, 0.95, 1.05, 1.15, 10], labels=["<0.85","0.85-0.95","0.95-1.05","1.05-1.15","1.15+"])
comp_attr = emp_c2.groupby("comp_band", observed=True)["is_leaver"].mean().mul(100).round(2)
print("Attrition rate by compa-ratio band (%):")
print(comp_attr)

t_c, p_c = st.ttest_ind(
    emp_c2.loc[emp_c2["is_leaver"], "compa_ratio"].dropna(),
    emp_c2.loc[~emp_c2["is_leaver"], "compa_ratio"].dropna(),
    equal_var=False,
)
print(f"\nCompa-ratio t-test: t={t_c:.3f}, p={p_c:.6f}")
print(f"Mean compa-ratio leavers: {emp_c2.loc[emp_c2['is_leaver'],'compa_ratio'].mean():.3f}")
print(f"Mean compa-ratio stayers: {emp_c2.loc[~emp_c2['is_leaver'],'compa_ratio'].mean():.3f}")

In [ ]:
# LENS 5: Legacy entity / acquisition cohorts
emp_c3 = emp.copy()
emp_c3["is_leaver"] = emp_c3["exit_date"].notna()

leg = emp_c3.groupby("legacy_entity_code").agg(
    headcount=("employee_id","count"),
    leavers=("is_leaver","sum"),
).assign(attr_rate=lambda d: round(d["leavers"]/d["headcount"]*100, 2))
print("Attrition by legacy entity (%):")
display(leg.sort_values("attr_rate", ascending=False))

ct3 = pd.crosstab(emp_c3["legacy_entity_code"], emp_c3["is_leaver"])
chi2_l, p_l, _, _ = st.chi2_contingency(ct3)
print(f"Legacy-entity chi2={chi2_l:.2f}, p={p_l:.6f}")

print(f"\ndays_to_fill range: {emp['days_to_fill'].min()}-{emp['days_to_fill'].max()}")
print(f"Mean days_to_fill leavers: {emp_c3.loc[emp_c3['is_leaver'],'days_to_fill'].mean():.1f}")
print(f"Mean days_to_fill stayers: {emp_c3.loc[~emp_c3['is_leaver'],'days_to_fill'].mean():.1f}")
t_d, p_d = st.ttest_ind(
    emp_c3.loc[emp_c3["is_leaver"], "days_to_fill"].dropna(),
    emp_c3.loc[~emp_c3["is_leaver"], "days_to_fill"].dropna(),
    equal_var=False,
)
print(f"days_to_fill t={t_d:.3f}, p={p_d:.6f}")

In [ ]:
# LENS 6: Performance trajectory — last review before exit
perf["review_date"] = pd.to_datetime(perf["review_date"], errors="coerce")
attr_perf = attr.merge(perf, on="employee_id", how="left")

last_review = attr_perf.sort_values(["employee_id","review_date"]).groupby("employee_id").tail(1)
last_review = last_review.loc[last_review["employee_id"].isin(attr["employee_id"])]

print("Last performance rating of leavers:")
print(last_review["performance_rating"].value_counts(normalize=True).mul(100).round(2))

emp_perf = emp.merge(perf, on="employee_id", how="left")
emp_last = emp_perf.sort_values(["employee_id","review_date"]).groupby("employee_id").tail(1)
print("\nLatest performance rating — all employees:")
print(emp_last["performance_rating"].value_counts(normalize=True).mul(100).round(2))

leaver_scores = perf[perf["employee_id"].isin(attr.loc[attr["regrettable_flag"],"employee_id"])].sort_values(["employee_id","review_date"])
trend = leaver_scores.groupby("employee_id")["goal_achievement_score"].agg(["first","last"]).dropna()
trend["delta"] = trend["last"] - trend["first"]
print(f"\nGoal score trend for regrettable leavers:")
print(f"  Mean first score: {trend['first'].mean():.1f}")
print(f"  Mean last score: {trend['last'].mean():.1f}")
print(f"  Mean delta: {trend['delta'].mean():.2f}")
t_g, p_g = st.ttest_rel(trend["first"], trend["last"])
print(f"  Paired t-test: t={t_g:.3f}, p={p_g:.6f}")

In [ ]:
# LENS 7: Survey wave momentum — did scores DROP before exit?
eng_sorted = eng.sort_values(["employee_id","wave_number"])

leaver_ids = attr.loc[attr["regrettable_flag"], "employee_id"]
leaver_eng = eng_sorted[eng_sorted["employee_id"].isin(leaver_ids)]

last_two = leaver_eng.groupby("employee_id").tail(2)
last_two["wave_pos"] = last_two.groupby("employee_id").cumcount(ascending=False)
pivoted = last_two.pivot_table(index="employee_id", columns="wave_pos", values=score_cols)

momentum = pd.DataFrame()
for c in score_cols:
    if c in pivoted.columns.get_level_values(0):
        try:
            newest = pivoted[(c, 0)]
            prev = pivoted[(c, 1)]
            delta = newest - prev
            momentum[c] = delta
        except KeyError:
            pass

print("Mean score change (last wave - previous wave) for regrettable leavers:")
print(momentum.mean().round(3))

print("\nOne-sample t-test (H0: delta = 0):")
for c in momentum.columns:
    vals = momentum[c].dropna()
    t, p = st.ttest_1samp(vals, 0)
    print(f"  {c:30s}: mean={vals.mean():+.3f}, t={t:+.3f}, p={p:.4f}, n={len(vals)}")

In [ ]:
# LENS 8: Hiring source quality
emp_c4 = emp.copy()
emp_c4["is_leaver"] = emp_c4["exit_date"].notna()

src = emp_c4.groupby("hire_source").agg(
    headcount=("employee_id","count"),
    leavers=("is_leaver","sum"),
).assign(attr_rate=lambda d: round(d["leavers"]/d["headcount"]*100, 2))
print("Attrition by hire_source (%):")
display(src.sort_values("attr_rate", ascending=False))

ct5 = pd.crosstab(emp_c4["hire_source"], emp_c4["is_leaver"])
chi2_s, p_s, _, _ = st.chi2_contingency(ct5)
print(f"Hire-source chi2={chi2_s:.2f}, p={p_s:.6f}")

In [ ]:
# LENS 9: Diversity & inclusion — gender, age_band, cultural_background
emp_c5 = emp.copy()
emp_c5["is_leaver"] = emp_c5["exit_date"].notna()

for col in ["gender", "age_band", "cultural_background"]:
    g = emp_c5.groupby(col).agg(
        headcount=("employee_id","count"),
        leavers=("is_leaver","sum"),
    ).assign(attr_rate=lambda d: round(d["leavers"]/d["headcount"]*100, 2))
    print(f"\nAttrition by {col}:")
    display(g.sort_values("attr_rate", ascending=False))
    ct = pd.crosstab(emp_c5[col], emp_c5["is_leaver"])
    chi2, p, _, _ = st.chi2_contingency(ct)
    print(f"{col} chi2={chi2:.2f}, p={p:.6f}")

In [ ]:
# LENS 10: Predictive risk score for active employees
emp_active = emp[emp["status"]=="active"].copy() if "status" in emp.columns else emp[emp["exit_date"].isna()].copy()

last_eng = eng.sort_values(["employee_id","wave_number"]).groupby("employee_id").tail(1)
emp_active = emp_active.merge(last_eng[["employee_id"]+score_cols], on="employee_id", how="left")

emp_active["low_engagement"] = emp_active[score_cols].mean(axis=1) < 3.5
emp_active["is_hipo"] = emp_active["hipo_flag"].fillna(False)
emp_active["underpaid"] = emp_active["compa_ratio"] < 0.9
emp_active["is_frontline"] = emp_active["role_level"].isin([1,2,3])

emp_active["risk_score"] = (
    emp_active["low_engagement"].astype(int)
    + emp_active["is_hipo"].astype(int)
    + emp_active["underpaid"].astype(int)
    + emp_active["is_frontline"].astype(int)
)

print("Risk score distribution (active employees):")
print(emp_active["risk_score"].value_counts().sort_index())

high_risk = (emp_active["risk_score"] >= 3).sum()
print(f"\nHigh-risk (score >= 3) active employees: {high_risk} ({high_risk/len(emp_active)*100:.1f}%)")

known_leavers = emp[emp["exit_date"].notna()].copy()
last_eng_l = eng.sort_values(["employee_id","wave_number"]).groupby("employee_id").tail(1)
known_leavers = known_leavers.merge(last_eng_l[["employee_id"]+score_cols], on="employee_id", how="left")
known_leavers["low_engagement"] = known_leavers[score_cols].mean(axis=1) < 3.5
known_leavers["is_hipo"] = known_leavers["hipo_flag"].fillna(False)
known_leavers["underpaid"] = known_leavers["compa_ratio"] < 0.9
known_leavers["is_frontline"] = known_leavers["role_level"].isin([1,2,3])
known_leavers["risk_score"] = (
    known_leavers["low_engagement"].astype(int)
    + known_leavers["is_hipo"].astype(int)
    + known_leavers["underpaid"].astype(int)
    + known_leavers["is_frontline"].astype(int)
)

print("\nRisk score — known leavers:")
print(known_leavers["risk_score"].value_counts(normalize=True).mul(100).round(2).sort_index())
print("\nRisk score — active:")
print(emp_active["risk_score"].value_counts(normalize=True).mul(100).round(2).sort_index())

from scipy.stats import mannwhitneyu
u, p_mw = mannwhitneyu(known_leavers["risk_score"], emp_active["risk_score"], alternative="greater")
print(f"\nMann-Whitney U (leavers > active): U={u:.0f}, p={p_mw:.6f}")
print(f"Mean risk score leavers: {known_leavers['risk_score'].mean():.2f}")
print(f"Mean risk score active: {emp_active['risk_score'].mean():.2f}")